### PR TITLE
Update dependencies (http4s 0.21.6)

### PR DESCRIPTION
**Pull request by leoniv**
Hi all! God work, thanks.
We slightly updated dependencies. Would you so kind to take it to the upstream and publish a new version of http4s-pac4j.

### CODE REVIEW

**Comment by leleuj** [comment]
The `README.md` states there is a v1 and a v2 of this library, but there was no release yet.

I think we can stay on version 1 and release. Can you fix the README? What's the `sbt` command to cut a v1.0.0 release? Thx

**Comment by leoniv** [comment]
@leleuj I've fixed the README. Sbt manual about publishing [here](https://www.scala-sbt.org/1.x/docs/Publishing.html)

**Comment by leleuj** [comment]
Thanks for your contribution. I will cut the release as soon as possible...

**Comment by leoniv** [comment]
Thanks

**Comment by leleuj** [comment]
This should be good. The release v1.0.0 should show up in the Maven central repository within a few hours.

**Pull request merged**
