### PR TITLE
Add support for SameSite Cookie Attribute

### PR DESCRIPTION
**Pull request by froth**
- make SameSite configurable in Http4sCookieSessionStore
- forward it in Http4sWebContext
- unit test for Http4sWebContext
- some small cleanup

### CODE REVIEW

**Comment by froth** [comment]
I am unsure whether this should be `4.2.1` or `4.3.0`.

**Comment by leleuj** [comment]
It should be a version 4.3.0 as it's more than a bugfix.

**Comment by froth** [comment]
Makes sense, I updated to 4.3.0-SNAPSHOT

**Comment by leleuj** [comment]
Excellent! I created a 4.2.x branch.

**Pull request merged**
