### PR TITLE
Fix concurrency issue in Http4sCacheSessionStore.

### PR DESCRIPTION
**Pull request by HuwCampbell**
Using a non-concurrent mutable hash map here can lead to infinite loops
when multiple logins occur simultaneously.

Ironically, the logging may be hiding this issue a bit, as when there is
a logger, the writing of it can block and act a bit like a synchronise.

We've hit this in prod, and it was taking down the server.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the fix.
I also updated the pac4j version to 5.4.2. Can you confirm everything is ok with this version before I release? Thanks

**Comment by HuwCampbell** [comment]
Sorry that's a bit harder than it should be in the wild. We vendored in a few versions back off of pac4j 4.5.0.

Apart from the change of `getOrCreateSessionId` to `getSessionId(context, true).get()` though our implementations of set and the cache update functions are the same.

We've been running with this change for almost a year.

I will try to test the demo app.

**Comment by HuwCampbell** [comment]
Actually there's probably 2 or 3 more changes I can make to improve the thread safety.

It looks like destroySession and renewSession have small threading issues. I'll see if I can get those in tomorrow.

**Comment by leleuj** [comment]
Excellent! Thanks.

**Comment by HuwCampbell** [comment]
Just an update here. I'm on holiday, but will try to get to this in May.

**Pull request merged**
